### PR TITLE
Add SANDAG 1 and 2 Zone examples

### PR DESCRIPTION
**Pull request by esanchez01**
Addresses: #431 

Adds the SANDAG 1 and 2 Zone examples. Additionally, updates the SANDAG 3 zone example structure and data.

### CODE REVIEW

**Comment by bstabler** [comment]
thanks @esanchez01.  can you issue a PR to https://github.com/ActivitySim/activitysim_resources as well when you get a chance?

**Comment by bstabler** [comment]
this is blocked by #457 and #458.  Once we pull those, we'll process this PR.

**Comment by bstabler** [comment]
@esanchez01 - let's make sure to update the 1, 2, and 3 zone system setups.  Thanks!

**Comment by bstabler** [comment]
on the 8/17 call @esanchez01 said he's still working on getting this ready.  Once pulled, @jpn-- will complete #439

**Comment by esanchez01** [comment]
@bstabler, this is now ready. PR has been issued to https://github.com/ActivitySim/activitysim_resources as well.

**Comment by bstabler** [comment]
#475

**Pull request merged**
