### PR TITLE
recode mazs in maz-to-maz table

### PR DESCRIPTION
**Pull request by jpn--**
Addresses #640

### CODE REVIEW

**Comment by jpn--** [comment]
@stefancoe We apparently don't have a CI test that sufficiently exercises this code to trigger the bug, and similarly we don't have a test that would verify this change will fix it, but I think it might be as simple as this.  Can you test this update and confirm it fixes your code?  If so, we'll merge this, and then maybe flag this to be something to be prioritized for actual unit testing when we're ready for that in a few months.

**Comment by stefancoe** [comment]
@jpn-- it fails on line 302 because the calculation on [line 301](https://github.com/camsys/activitysim/blob/bugfix-640/activitysim/core/los.py#L301) in los.py results in a int16 overflow, but I got it to work by changing it to this:

`df["i"] = df.OMAZ.astype(np.int32) * self.maz_ceiling.astype(np.int32) + df.DMAZ.astype(np.int32)`

**Comment by stefancoe** [comment]
@jpn-- it looks like when running with legacy config settings, self.maz_ceiling is an int instead of a numpy.int32 and `self.maz_ceiling.astype(np.int32)` fails. This seems to work for all cases:

`df["i"] = df.OMAZ.astype(np.int32) * self.maz_ceiling + df.DMAZ.astype(np.int32)`

**Comment by jpn--** [comment]
Superceded by #654

**Pull request closed without merging**
