### PR TITLE
feat: add optional sha256 to example manifest

### PR DESCRIPTION
**Pull request by jpn--**
This change allows an optional sha256 checksum to be added in the examples manifest.  If the file to be downloaded already exists locally in the correct place and matches the checksum, we no longer re-download the file, just use the copy we already have. This can prevent upcoming benchmarking tool #439 from pounding relentlessly on activitysim_resources repo, by caching the large file downloads. (Added bonus, if we do need to download we can validate the checksum after the download and make sure the file is what was expected.)

### CODE REVIEW

**Comment by bstabler** [comment]
this is a nice improvement.  @jpn-- can we add checksums to each example posted in activitysim_resources?

**Comment by bstabler** [comment]
@jpn-- please PR to develop when ready

**Comment by jpn--** [comment]
This PR is now ready to merge into `develop`.

**Comment by bstabler** [comment]
Looks good.  @jpn-- can you update the docs, probably the development and/or example rst pages, with some notes about the checksums and how to update them?  Thanks.

**Comment by bstabler** [comment]
@jpn-- to update documentation

**Review by bstabler — COMMENTED** [review]
see comments in issue

**Comment by jpn--** [comment]
@bstabler I've added some docs on checksums.  If you agree they are sufficient this is ready to merge.

**Comment by bstabler** [comment]
looks good, thanks

**Pull request merged**
