### PR TITLE
Vehicle Type Alts Filtering Bug Fix

### PR DESCRIPTION
**Pull request by dhensle**
PR for #789

### CODE REVIEW

**Comment by jpn--** [comment]
When we fix a bug, we need to have a test that proves it's fixed (and so it stays fixed).

**Comment by i-am-sijia** [comment]
Need to update documentation:
> Ok, let's add `REQUIRE_DATA_FOR_ALL_ALTS` to the model documentation, and update the following blurb to remove "must be included in the file" -
> 
> https://github.com/ActivitySim/activitysim/blob/a8e755f96d0e32633a6d3657c4878e3b6a37e59a/docs/models.rst#L448-L451

**Comment by jpn--** [comment]
I opened a PR #796 to bring ActivitySim's config settings up-to-date with Pydantic 2.0, which should address your most recent test failure (at least in part).

**Comment by dhensle** [comment]
Thanks! The test was passing locally, so I expect the update should fix the test completely.

**Pull request merged**
