### PR TITLE
Adding MWCOG + small example dataset

### PR DESCRIPTION
**Pull request by AndrewTheTM**
This is the MWCOG example setup and small example dataset.

### CODE REVIEW

**Comment by AndrewTheTM** [comment]
Fixed code style issues in script causing failed test

**Comment by jpn--** [comment]
Your tests were failing cause you opened this PR against `master` instead of `develop`.  The `master` branch currently can't pass tests because the latest version of numba triggers a deprecation warning from numpy.  This has been fixed in `develop`, but the fix is not yet released in `master`.

More generally, we don't allow PRs against `master`, only against `develop`, see [here](https://activitysim.github.io/activitysim/development.html#working-together-in-the-repository).  I moved it, and I expect the tests will pass in travis when run with the `develop` code.

**Comment by AndrewTheTM** [comment]
Thanks @jpn-- , I wasn't sure if it was the same since it's data (now I know!)

**Comment by AndrewTheTM** [comment]
@jpn-- Do I need to do something to cause the tests to re-run? The last test was before you moved this to develop.

**Pull request closed without merging**
