### PR TITLE
Visualization Pull Request

### PR DESCRIPTION
**Pull request by danielsclint**
#443: Visualization
#533: np.MachAr Deprecation (Hotfix)

Currently in DRAFT

# Todo

- [x] @danielsclint: Move documentation from [Google Docs](https://docs.google.com/document/d/16l7MN2QaesesWvksGQjv_o39zf-bbDsf3mF9GV4vYeo/edit) to Sphinx
- [x] @danielsclint: Fix path to data folder for tests.
- [x] @chesterharvey: Provide 1-2 sentence response to "Review Criteria Responses" below.
- [x] @chesterharvey: Create docstrings for summarize.py methods
- [ ] @e-lo: Perform an initial code review.
- [ ] @joecastiglione / @wusun2: Test implementation in region.
- [ ] @joecastiglione: Should we just add simwrapper as an overall ActivitySim dependency and forgo any extra installs?

# Review Criteria Responses
1. Does it contain all the required elements, including a runnable example, documentation, and tests?  
_Yes. A runnable example is incorporated into `example_mtc`. Documentation has been updated to explain yaml and csv expression files used to configure the summarize model. New tests were created to check csv outputs from a minimal example._  

2. Does it implement good methods (i.e. is it consistent with good practices in travel modeling)?  
_Yes. The summarize model produces outputs in a flexible, industry-standard format (csv) and integrates fully into the Activitysim modeling pipeline. It does not impact travel modeling results, but operates on these results._

3. Are the runtimes reasonable and does it provide documentation justifying this claim?  
_Yes. The model adds only seconds to model runtime on a standard workstation._  

4. Does it include non-Python code, such as C/C++? If so, does it compile on any OS and are compilation instructions included?  
_Yes and no. The changes to the ActivitySim package are completely implemented in Python, but it does add an additional dependency to [SimWrapper](https://github.com/simwrapper/simwrapper)._  

5. Is it licensed with the ActivitySim license that allows the code to be freely distributed and modified and includes attribution so that the ‘provenance’ of the code can be tracked? Does it include an official release of ownership from the funding agency if applicable?  
_This work was done under contract to AMPO Research Foundation, and, presumably, AMPO Research Foundation is providing the changes without any additional licensing beyond the existing ActivitySim licensing._

6. Does it appropriately interact with the data pipeline (i.e. it doesn't create new ways of managing data)?
_The model ingests data from the pipeline and produces csv files in a standard "output" directory._

7. Does it include regression tests to enable checking that consistent results will be returned when updates are made to the framework?
_The model does not impact modeling outputs. As such, no regression testing has been done._  

8. Does it include sufficient test coverage and test data for existing and proposed features?
_Yes. It includes a new test module with associated configuration files and input data._

9. Any other comments or suggestions for improving the developer experience?
_No_

### CODE REVIEW

**Comment by bhargavasana** [comment]
"summarize" model is not added in "configs_mp/settings.yaml". When the MTC full example is run with multiprocessing settings (activitysim run -c configs_mp -c configs -o output -d data), no summarize outputs are generated. I suggest adding "summarize" model to "configs_mp/settings.yaml" also.

I just used "configs/settings.yaml" with "resume_after: write_tables" setting to run only "summarize" model. It took more than 70 minutes. This is just a note that runtime seems high and this maybe due to how this ActivitySim feature is setup.

summarize_only_runtime

**Comment by bhargavasana** [comment]
There appears to be a typo in activitysim/examples/example_mtc/configs/summarize.yaml on line no. 5 - `DF: trips_mergerd` instead of `DF: trips_merged`. However, running summarize model runs through without an error or warning.

**Comment by bhargavasana** [comment]
I encounter a few errors when I try to pull up the local full run example dashboard. Some of these errors maybe related to the typo above. I will re-run summarize model after fixing the typo and provide an update (it takes over 70 minutes as noted above).
asimdash_error

**Comment by esanchez01** [comment]
@bhargavasana, I am also testing this PR on SANDAG's behalf and can possibly shed some light on a couple of your issues.

If you have not pulled the latest commits to this PR, I would suggest you do so as I saw a reduction in run time after pulling them in. I believe this reduction was in part due to the *summarize* step no longer writing out the large `trips_merged` and `persons_merged` tables as shown [here](https://github.com/wsp-sag/activitysim/blob/0c025b1e5da2141a72febaeba2f9e22e44e68086/activitysim/abm/models/summarize.py#L308).

As for the dashboard errors, they appear to be due to a few reasons. The upper row of the dashboard should be displaying a table as specified by `topsheet.yaml`. However, it does not appear, as in your screenshot, because `topsheet.yaml` references the wrong table names -- it should be pointing to *person_tours.csv* instead of *tours_count.csv* and *person_trips.csv* instead of *trips_count.csv*. If you look at `summarize.csv`, the unique values in the column *output* are the tables that are generated. Also, the 'VMT / Employee' map does not finish loading, as in your screenshot, due to the underlying table not being generated by the *summarize* step.

**Comment by chesterharvey** [comment]
> There appears to be a typo in activitysim/examples/example_mtc/configs/summarize.yaml on line no. 5 - `DF: trips_mergerd` instead of `DF: trips_merged`. However, running summarize model runs through without an error or warning.

Thanks @bhargavasana  for catching this syntax error. Just corrected it.

**Comment by bhargavasana** [comment]
Thank you @esanchez01 and @chesterharvey. I implemented your suggestions and everything is now working on my end.

- After getting the update where big tables are not written out by `summarize`, the step takes about 30 minutes.
- In addition to the tweaks that @esanchez01 suggested to `topsheet.yaml`, I needed to update `dashboard-1-summary.yaml`
`dataset: 'vmt_per_employee_by_work_taz.csv'` -> `dataset: 'vmt_per_capita_by_work_taz.csv'`
`datasetValue: 'vmt'` -> `datasetValue: 'vmt_per_capita_by_home_taz'`
`datasetValue: 'vmt'` -> `datasetValue: 'vmt_per_capita_by_work_taz'`

**Comment by esanchez01** [comment]
I am attaching the assessment slides presented during the 1/18/22 technical call and the corresponding memo:
[Visualizer_Assessment_slides_SANDAG.pdf](https://github.com/ActivitySim/activitysim/files/7892201/Visualizer_Assessment_slides_SANDAG.pdf)
[Visualizer_Assessment_memo_SANDAG.pdf](https://github.com/ActivitySim/activitysim/files/7892221/Visualizer_Assessment_memo_SANDAG.pdf)

**Review by JoeJimFlood — APPROVED** [review]

**Comment by JoeJimFlood** [comment]
One comment I will make: I feel as though the way the aggregation maps are currently defined isn't super user-friendly. For example, the major access trip mode in the MTC example it's currently defined as follows:

```
map:
        DRIVEALONEFREE: SOV
        DRIVEALONEPAY: SOV
        SHARED2FREE: HOV
        SHARED2PAY: HOV
        SHARED3FREE: HOV
        SHARED3PAY: HOV
        WALK_LOC: Walk to Transit
        WALK_LRF: Walk to Transit
        WALK_EXP: Walk to Transit
        WALK_HVY: Walk to Transit
        WALK_COM: Walk to Transit
        DRIVE_LOC: Drive to Transit
        DRIVE_LRF: Drive to Transit
        DRIVE_EXP: Drive to Transit
        DRIVE_HVY: Drive to Transit
        DRIVE_COM: Drive to Transit
        WALK: Non-Motorized
        BIKE: Non-Motorized
        TAXI: Ride Hail
        TNC_SINGLE: Ride Hail
        TNC_SHARED: Ride Hail
```

While this can be directly input into the ``pd.Series.map()`` function, the same information could be given by the following:

```
map:
    SOV:
        DRIVEALONEFREE
        DRIVEALONEPAY
    HOV:
        SHARED2FREE
        SHARED2PAY
        SHARED3FREE
        SHARED3PAY
    Walk to Transit:
        WALK_LOC
        WALK_LRF
        WALK_EXP
        WALK_HVY
        WALK_COM
    Drive to Transit:
        DRIVE_LOC
        DRIVE_LRF
        DRIVE_EXP
        DRIVE_HVY
        DRIVE_COM
    Non-Motorized:
        WALK
        BIKE
    Ride Hail:
        TAXI
        TNC_SINGLE
        TNC_SHARED
```

This is less repetitive and more readable. Something like this would then need to be added before line 289 of summarize.py and 290 would need to be changed to use map instead of agg['map'] (I can make the change if needed):
```
map = {}
for value in agg['map']:
    for key in agg['map'][value]:
        map[key] = value
```

**Pull request merged**
