### PR TITLE
ARC Updates

### PR DESCRIPTION
**Pull request by danielsclint**
Initial PR for ARC Updates

### CODE REVIEW

**Comment by bstabler** [comment]
Thanks @danielsclint.  I'm going to accept and then add an additional example to exercise the ARC extensions to TM1.  This will take the form of a new entry here - https://github.com/ActivitySim/activitysim/blob/develop/activitysim/examples/example_manifest.yaml.

**Comment by bstabler** [comment]
@danielsclint - the `example_mtc_arc_extensions ` on `develop` fails in one of the new ARC submodels.  Please fix so we can release the next version.  Here's how to create and run this new example.  Thanks. 

```
activitysim create -e example_mtc_arc_extensions -d test_example_mtc_arc_extensions
activitysim run -c configs_arc -c configs -o output -d data
```

**Comment by danielsclint** [comment]
You defined trip_scheduling and the two ARC trip_scheduling models to run in the same run.

image

You should only define one or the other.

image

**Comment by bstabler** [comment]
Thanks.  It is now fixed.  This is a good example of why we need to include runnable examples with contributions.

**Pull request merged**
