### PR TITLE
Improved distribution system for conda-forge and pip

### PR DESCRIPTION
**Pull request by jpn--**
This branch contains work on #424

### CODE REVIEW

**Comment by bstabler** [comment]
includes work on #437 as well

**Comment by jpn--** [comment]
Any objection to merging this PR into master, and tagging it as v1.0.2?  This PR is operationally identical to 1.0.1, just with the dependencies fixed so orca is a dependency and zbox is gone.  To make a clean version for conda-forge for #424, conda-forge policy (very reasonably) wants to build code as it appears from the main repo and not a PR.

**Comment by bstabler** [comment]
As discussed 7/8, we can't publish to conda forge until the code is in master, but having the code in master also means we've released the code according to our [Release Process](https://activitysim.github.io/activitysim/development.html#releases). So, @jpn-- is updating the docs as if these changes are live, and we're working on some additional improvements to make releases more automated - for example, #139.

**Comment by jpn--** [comment]
I can only work on #139 in a branch of the main repo, not on my fork.  So, closing this in favor of the same branch I've pushed now the the main repo.

**Pull request closed without merging**
